name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mypostgres
        ports:
          - 5432:5432
        # Use health checks to wait for the database to be ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # or the version you're using

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            server/node_modules
            client/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Server Dependencies
        run: npm install
        working-directory: server

      - name: Run Server Tests
        run: npm test
        working-directory: server
        env:
          PORT: 5001
          PGUSER: postgres
          PGHOST: postgres # Use the service name as the host
          PGPASSWORD: password
          PGDATABASE: mypostgres
          PGPORT: 5432
          JWT_SECRET: ea6cdac0714a5abefa0b977dcf2e80abcb0d607f564e97d3fc6f759db6b719b9
