name: Basic Dependency Check

on: [push, pull_request]

jobs:
  check-backend-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Adjust to your project's Node.js version
    
    - name: Install backend dependencies
      run: npm install
      working-directory: ./server # Adjust if your server directory is different
    
  check-frontend-dependencies:
    runs-on: ubuntu-latest
    needs: check-backend-dependencies
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Ensure this matches your frontend Node.js version
    
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./client # Adjust if your client directory is different
